// scripts.js

// Local SVG images for reliable loading
const energyTopics = [
    {
        img: 'images/solar.svg',
        title: 'Solar Energy',
        desc: 'Harnessing the power of the sun through photovoltaic panels and solar thermal systems.',
        url: 'pages/solar.html'
    },
    {
        img: 'images/wind.svg',
        title: 'Wind Energy',
        desc: 'Clean energy generated by wind turbines converting kinetic energy into electricity.',
        url: 'pages/wind.html'
    },
    {
        img: 'images/hydro.svg',
        title: 'Hydroelectric Power',
        desc: 'Electricity produced from the movement of water, typically in dams and rivers.',
        url: 'pages/hydro.html'
    },
    {
        img: 'images/geothermal.svg',
        title: 'Geothermal Energy',
        desc: 'Heat energy from the Earth used for electricity generation and heating.',
        url: 'pages/geothermal.html'
    },
    {
        img: 'images/biomass.svg',
        title: 'Biomass Energy',
        desc: 'Renewable energy from organic materials like plants and waste.',
        url: 'pages/biomass.html'
    },
    {
        img: 'images/nuclear.svg',
        title: 'Nuclear Energy',
        desc: 'High-energy output from nuclear fission processes in power plants.',
        url: 'pages/nuclear.html'
    }
];

// Power icon with local fallback
document.getElementById('power-icon').src = 'images/PowerIcon.png';
document.getElementById('power-icon').onerror = () => {
    this.src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAiIGhlaWdodD0iODAiIHZpZXdCb3g9IjAgMCA4MCA4MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGNpcmNsZSBjeD0iNDAiIGN5PSI0MCIgcj0iMzUiIGZpbGw9IiM0RkFGREUiLz4KPHBhdGggZD0iTTI1IDM1TDQwIDI1TDU1IDM1IiBzdHJva2U9IndoaXRlIiBzdHJva2Utd2lkdGg9IjQiLz4KPHBhdGggZD0iTTI1IDQ1TDQwIDU1TDU1IDQ1IiBzdHJva2U9IndoaXRlIiBzdHJva2Utd2lkdGg9IjQiLz4KPC9zdmc+';
};

// Populate gallery
function populateGallery() {
    const gallery = document.getElementById('topic-gallery');
    energyTopics.forEach(topic => {
        const link = document.createElement('a');
        link.href = topic.url;
        link.className = 'gallery-link';
        link.innerHTML = `
            <div class="gallery-item">
                <img src="${topic.img}" alt="${topic.title}" loading="lazy">
                <h3>${topic.title}</h3>
                <p>${topic.desc}</p>
            </div>
        `;
        gallery.appendChild(link);
    });
}

// Load CSV data (sample embedded since fetch may need server)
const csvData = `Year,Source,Consumption_TWh
2020,Solar,250
2020,Wind,380
2020,Hydro,4200
2020,Geothermal,15
2020,Biomass,60
2020,Nuclear,2500
2021,Solar,320
2021,Wind,420
2021,Hydro,4150
2021,Geothermal,16
2021,Biomass,62
2021,Nuclear,2480
2022,Solar,410
2022,Wind,460
2022,Hydro,4100
2022,Geothermal,17
2022,Biomass,65
2022,Nuclear,2450`;

// Parse CSV
function parseCSV(csv) {
    return csv.split('\n').slice(1).map(line => {
        const [year, source, consumption] = line.split(',');
        return { year: parseInt(year), source, consumption: parseFloat(consumption) };
    });
}

// Populate table
function populateTable(data) {
    const tbody = document.getElementById('table-body');
    data.forEach(row => {
        const tr = document.createElement('tr');
        tr.innerHTML = `
            <td>${row.year}</td>
            <td>${row.source}</td>
            <td>${row.consumption.toLocaleString()}</td>
        `;
        tbody.appendChild(tr);
    });
}

// Simple bar chart
function drawChart(data) {
    const canvas = document.getElementById('energy-chart');
    const ctx = canvas.getContext('2d');
    
    // Clear
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    
    // Group by source (latest year)
    const latest = 2022;
    const sources = {};
    data.filter(d => d.year === latest).forEach(d => {
        sources[d.source] = d.consumption;
    });
    
    const sourceNames = Object.keys(sources);
    const maxVal = Math.max(...Object.values(sources));
    const barWidth = 60;
    const spacing = 80;
    let x = 50;
    
    sourceNames.forEach((source, i) => {
        const height = (sources[source] / maxVal) * 300;
        ctx.fillStyle = '#3498db';
        ctx.fillRect(x, canvas.height - height - 50, barWidth, height);
        ctx.fillStyle = '#2c3e50';
        ctx.font = '12px Arial';
        ctx.textAlign = 'center';
        ctx.fillText(source, x + barWidth/2, canvas.height - 10);
        ctx.fillText(sources[source].toLocaleString(), x + barWidth/2, canvas.height - height - 55);
        x += spacing;
    });
    
    // Axes
    ctx.strokeStyle = '#bdc3c7';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(40, canvas.height - 50);
    ctx.lineTo(canvas.width - 20, canvas.height - 50);
    ctx.lineTo(canvas.width - 20, 50);
    ctx.stroke();
}

// Simple nav active state (for home)
document.addEventListener('DOMContentLoaded', () => {
    populateGallery();
    const data = parseCSV(csvData);
    populateTable(data);
    drawChart(data);
    
    // Set home nav active
    const homeLink = document.querySelector('.nav-links a[href="index.html"], .nav-links a[href="./index.html"]');
    if (homeLink) homeLink.classList.add('active');
});
